### ISSUE TITLE
Dont get it worked out when I parse an url

### ISSUE THREAD

**Issue by Thoompje** [jmoiron/speedparser#12]
I get an error when I try to parse something.
I try to parse this url: http://rss.cnn.com/rss/money_news_companies.rss

I work with Python3.4 and tornadoweb. So I made a change in the 'speedparser.py' file. I changed urlparse into urllib.parse, because urlparse is not longer supported in python3.

The error is:
<code>
{'bozo_tb': 'Traceback (most recent call last):\n  File "C:\\Python34\\lib\\site-packages\\speedparser\\speedparser.py", line 685, in parse\n    parser = SpeedParser(document, cleaner, unix_timestamp, encoding)\n  File "C:\\Python34\\lib\\site-packages\\speedparser\\speedparser.py", line 582, in __init__\n    self.tree = tree.getroottree()\nAttributeError: \'NoneType\' object has no attribute \'getroottree\'\n', 'bozo': 1, 'bozo_exception': AttributeError("'NoneType' object has no attribute 'getroottree'",), 'feed': {}, 'entries': []}
</code>
